# Generated by Django 5.2.9 on 2025-12-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('intrusion', 'Intrusion'), ('malware', 'Malware'), ('anomaly', 'Anomaly'), ('bruteforce', 'Brute Force Attack'), ('ddos', 'DDoS Attack'), ('phishing', 'Phishing Attempt'), ('ransomware', 'Ransomware'), ('data_exfiltration', 'Data Exfiltration'), ('unauthorized_access', 'Unauthorized Access'), ('privilege_escalation', 'Privilege Escalation'), ('policy_violation', 'Policy Violation'), ('suspicious_login', 'Suspicious Login'), ('command_execution', 'Malicious Command Execution'), ('file_integrity', 'File Integrity Violation'), ('network_scan', 'Network Scanning'), ('bot_activity', 'Bot Activity'), ('configuration_change', 'Unauthorized Configuration Change'), ('vulnerability_detected', 'Vulnerability Detected')], max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('asn', models.CharField(blank=True, max_length=100, null=True)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_vpn', models.BooleanField(default=False)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('os_family', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_family', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent_string', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('headers_dump', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
