# Generated by Django 5.2.9 on 2025-12-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('intrusion', 'Intrusion'), ('malware', 'Malware'), ('anomaly', 'Anomaly'), ('bruteforce', 'Brute Force Attack'), ('ddos', 'DDoS Attack'), ('phishing', 'Phishing Attempt'), ('ransomware', 'Ransomware'), ('data_exfiltration', 'Data Exfiltration'), ('unauthorized_access', 'Unauthorized Access'), ('privilege_escalation', 'Privilege Escalation'), ('policy_violation', 'Policy Violation'), ('suspicious_login', 'Suspicious Login'), ('command_execution', 'Malicious Command Execution'), ('file_integrity', 'File Integrity Violation'), ('network_scan', 'Network Scanning'), ('bot_activity', 'Bot Activity'), ('configuration_change', 'Unauthorized Configuration Change'), ('vulnerability_detected', 'Vulnerability Detected'), ('login_fail', 'Login Failure'), ('sql_injection', 'SQL Injection Attempt'), ('file_mod', 'Sensitive File Modification'), ('system_scan', 'Vulnerability Scan')], max_length=100),
        ),
    ]
