# Generated by Django 5.2.9 on 2025-12-25 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('alert_assigned', 'Alert Assigned'), ('alert_resolved', 'Alert Resolved'), ('alert_acknowledged', 'Alert Acknowledged'), ('user_registered', 'User Registered'), ('profile_update', 'Profile Updated')], max_length=50)),
                ('module', models.CharField(choices=[('accounts', 'Accounts & Auth'), ('alerts', 'Alert Management'), ('events', 'Event Monitoring'), ('system', 'System Configuration')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
